#check if both the operators are same object or not
# if both variable are same it will return the value True
#if both the varaible are not same it will return the value False
''' 
identity operators
is - returns True if both variable are the same object
is not- returns True if both variables are not the same
'''
#identity operators
x= 5
y=5
print("if x is y:",x is y)
print("if x is not y:", x is not y)

